### ISSUE TITLE
Prototipo

### ISSUE THREAD

**Issue by LucasLopesFrazao** [UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon#5]
O de alta tem que ter, o de baixa, se der deu.

Entrega dia 14/09 ás 23:59

Fazer só depois do brainstorm

Colocar o link do figma para quem quiser acompanhar

**Comment by Mateuszinnn** [comment]
Link para o protópico:

https://www.figma.com/file/7yoAVSlriOacp0aC2kI1l0/G03-Amazon---ADS?type=design&node-id=0%3A1&mode=design&t=TXA5T4PDLjZUXR2X-1
