### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by LucasLopesFrazao** [UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon#7]
Todos devem fazer o rich picture do projeto a fim de evidenciar uma visão do sistema por todos.

Entrega: 23:59 do dia 08/09

Upar em algum lugar e colocar o link aqui nos comentários.

**Comment by LucasLopesFrazao** [comment]
![Image](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/89523373/0144d598-7394-4764-89a6-7ae80d4bbf6a)

**Comment by luclopesr** [comment]
![Image](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/88348202/aafcc342-c5a7-4cab-83a1-24184b7cc5c8)

**Comment by pedrohelias** [comment]
https://drive.google.com/file/d/1AT5oaWXl4ZC5TlrRnmaZ-GTPeci-cojh/view?usp=sharing


![Image](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/30875663/dfbf7eae-abf9-4958-b476-4a11efd06d17)

**Comment by SamuelGSouza** [comment]
https://unbbr-my.sharepoint.com/:u:/g/personal/211030881_aluno_unb_br/EVUOK0a3wp9JhUns0wvUnPUB_ZQVwuu18IHo-tr9SXGPYQ?e=aiPOJW

![🥱](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/72769279/21f91878-bc15-4c2e-9982-f6ba3300addd)

**Comment by oo7gabriel** [comment]
![Rich Picture](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/43484906/cab7905c-50f9-4d8e-9761-12c66d17a1d2)

**Comment by HenriPucci** [comment]
![Image](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/87674351/621ec9c2-d7ac-4504-a5e7-0304161c94a8)

**Comment by LucasLopesFrazao** [comment]
![Image](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/89523373/fb1ff2f9-932c-4883-b6e6-fd668c381bc9)

**Comment by Mateuszinnn** [comment]
![image](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/80906504/37942bcc-758b-4837-97b6-56ad935b015d)

**Comment by Mateuszinnn** [comment]
![image](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/80906504/94647944-4564-47b7-b7e2-b3c978c8c796)

**Comment by chaydson** [comment]
![Image](https://github.com/UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon/assets/90580219/c373fa47-437e-4950-91e4-7ea7c3b239ff)
