### ISSUE TITLE
Estudos para apresentação (01/09)

### ISSUE THREAD

**Issue by LucasLopesFrazao** [UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon#9]
Realizar estudos sobre:

O estudo deve ser feito também em texto para o pessoal do slide conseguir trabalhar em cima.

- Introdução (Origem & Principais Bases +/- 2min)
Membro: Henrique

- Visão Geral (Ciclo & Princípios & Boas Práticas +/- 5min)
Membro: Chaydson e Frazão

- Prós & Contras (+/- 1min)
Membro: Lopes

- Conclusão (Exemplos de Uso +/- 1min)
Membro: Helias

- Referências (+/- 1min)
Membro: Frazão

Entrega: até 31/08 ás 22:00

**Comment by pedrohelias** [comment]
## Tópico de exemplo de uso ##
<a href="https://docs.google.com/document/d/1_Z0_S5ZpLtXu4u_0zAZmgdIJZadAfOQaCi0dVlYWfFQ/edit?usp=sharing">link</a>

**Comment by LucasLopesFrazao** [comment]
## Tópico de visão geral
[Google docs](https://docs.google.com/document/d/1B-mC_RGJIUDuPEGlWoT5_gNLL4DmosgZjio4tEVxcfs/edit)
